# Dependencies
markdown:         redcarpet

redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter:      pygments

# Permalinks
permalink:        pretty
#permalink: /posts/:title

# Setup
title :           Dark Side
tagline:          ''
description:      'Free talk'
url:              http://zer4tul.github.io
baseurl:          '/'
paginate:         5

author :
  name : Zeratul Ke
  email : zer4tul@gmail.com
  github : zer4tul
  twitter : zer4tul

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/zer4tul
production_url : http://zer4tul.github.io
disqus_shortname: the-dark-side
